# 一、什么是情感分析（Sentiment Analysis）？
一句话解释：  

情感分析就是让电脑自动判断一段文本的“情绪倾向”——是积极、消极，还是中性。  

你可以把它理解为：  

电脑在读评论、新闻、公告、文章时，尝试回答：  

• 情绪怎么样？（正面 / 负面）  

• 程度如何？（强烈 positive？轻微 negative？）  

常见应用包括：  

• 电商上判断用户评论是好评还是差评  

• 金融领域判断公司年报的语气是否乐观  

• 社交媒体分析大众对某个政策/事件的态度  

• 客服系统自动识别“愤怒客户”优先处理

# 二、情感分析怎么做？（两大主流方法）
方法 1：词典法（Dictionary-based）  

课堂最容易讲清楚的一种 ➜ 你现在 Notebook 中就是用这个。  

核心思想：  

提前准备好“带情绪的词”列表，然后统计文本中出现了多少。  

例：  

• 正向词典：优秀、增长、满意、顺利、改善…  

• 负向词典：亏损、下降、风险、困难、失败…  

步骤：  

1. 准备情感词典（积极词 + 消极词）

2. 对文本分词（例如用 Jieba）
 
3. 统计正向词数 / 负向词数

4. 得到情感分数（如：pos – neg）

词典法特点：简单、透明、可解释、容易教学。  

方法 2：机器学习 / 深度学习法  

不依赖词典，而是让模型自己学：  

• 经典算法：SVM、朴素贝叶斯、逻辑回归  

• 深度学习：LSTM、BERT、RoBERTa、GPT 等预训练模型  

需要大量标注数据，例如：  

• “这手机太棒了！” → 标签：正面  

• “糟糕透了，不会再买。” → 标签：负面  

模型学到语气、上下文关系、反讽等，比词典法更聪明。

# 三、中英文常见情感词典
下面列出教学时常用、比较权威的：  （网上下载）

🔵 中文情感词典  

1. NTUSD（台湾大学情感词典）← 很常用  <br>
• 有正向词、负向词 <br>
• 开源，学界广泛使用 <br>

2. 哈工大情感词典（Hownet / Dalian University of Technology）<br>
• 包含情感词、评价词、情绪词 <br>
• 较大且细分类别多 <br>

3. BosonNLP 情感词典 <br>
• 来源于微博语料，适合社交媒体分析 <br>

4. 清华大学 THUOCL 词典 <br> 
• 多类别词典，其中包含评价类词汇 <br> 

🔵 英文常用情感词典 <br>
1. NRC Emotion Lexicon（NRC-EmoLex） <br>
• 包含 8 类情绪：joy、anger、fear、sadness… <br>
• 国际影响力很大 <br>

2. AFINN <br>
• 每个词带情绪分数（-5 到 +5） <br>
• 简单好用 <br>

3. VADER（NLP 中的经典）<br> 
• 专为社交媒体设计<br>
• Python 中 nltk.sentiment.vader 直接调用 <br>
• 强调符号、表情符、“!!!” 等效果 <br>

4. LIWC（收费）<br>
• 心理语言分析词典<br>
• 学术界应用广泛（尤其心理学研究 <br>

# 四、这些词典是怎么做出来的？ 
词典不是凭空生成的，它通常来自：<br>
1. 专家人工标注 <br>
语言学/心理学专家手动整理出情感词。 <br>

2. 大规模语料统计 <br>
从大量文本中，根据词语出现的上下文判断其情绪。 <br>

3. 群体投票方式（如 NRC） <br>
通过众包（crowdsourcing）让多人给词语贴标签。 <br>

4. 计算方法自动扩展词表 <br>
如：Word2Vec 找同义词 → 扩充词典规模。 <br>

# 文本情感计算
1. 根据词典统计正负情感词个数
2. 机器学习

# 实现步骤
1. 读取data/dict中的词典（自定义）
2. 读取data/txts文本中的文本text
3. 定义计算情感的函数senti <br>
   计算文本情感得分senti(text)
5. 新建csv，将计算结果存储到csv中

## 1. 读取data/dict中的词典

In [1]:
# 从 datanew/dict/positive.txt 文件中读取“正向情感词典”
# open(...) 打开文件；encoding='gbk' 表示文件编码是 gbk（很多旧中文词典是 GBK 编码）
# .read() 读取整个文本内容为一个长字符串
# .split('\n') 按换行符分割成列表，每行一个情感词
poss = open('datanew/dict/positive.txt', encoding='gbk').read().split('\n')

# 从 datanew/dict/negative.txt 文件读取“负向情感词典”
# 逻辑与上一行完全相同，只是换成 negative.txt 文件
negs = open('datanew/dict/negative.txt', encoding='gbk').read().split('\n')

# 查看负向词典的内容（通常是一个 list，里面是每一行的词语）
negs

['投资',
 '下降',
 '转型',
 '成本',
 '控制',
 '调整',
 '影响',
 '管控',
 '风险',
 '投入',
 '竞争',
 '减少',
 '面对',
 '降低',
 '变化',
 '压力',
 '责任',
 '挑战',
 '下滑',
 '市场竞争',
 '困难',
 '改进',
 '放缓',
 '严峻',
 '披露',
 '激烈',
 '下游',
 '低迷',
 '下行',
 '过剩',
 '处置',
 '加剧',
 '防范',
 '整改',
 '调控',
 '波动',
 '克服',
 '仿制',
 '稳中求进',
 '退出',
 '亏损',
 '有限',
 '应急',
 '冲击',
 '不利',
 '攻坚克难',
 '低于',
 '回落',
 '严控',
 '经营风险',
 '负债',
 '不利因素',
 '持平',
 '生产成本',
 '扣除',
 '缓慢',
 '价格上涨',
 '成本费用',
 '乏力',
 '下跌',
 '整治',
 '停产',
 '高位',
 '风控',
 '污染物',
 '缺陷',
 '降低生产',
 '矛盾',
 '低位',
 '疲软',
 '尚未',
 '终止',
 '隐患',
 '债务',
 '未能',
 '减值',
 '错综复杂',
 '资产负债',
 '日趋激烈',
 '震荡',
 '成本上升',
 '淘汰',
 '降幅',
 '瓶颈',
 '差距',
 '高压',
 '最低',
 '遗留问题',
 '复杂多变',
 '困境',
 '难题',
 '减亏',
 '持续保持',
 '迎难而上',
 '损失',
 '制约',
 '审慎',
 '难以',
 '异常',
 '低端',
 '逆势',
 '降价',
 '不景气',
 '超低',
 '落后',
 '安全隐患',
 '萎缩',
 '不确定性',
 '剔除',
 '趋稳',
 '严峻形势',
 '紧张',
 '急剧',
 '低速',
 '下沉',
 '坏账',
 '危机',
 '限制性',
 '关闭',
 '不振',
 '收紧',
 '趋缓',
 '缺乏',
 '薄弱环节',
 '趋严',
 '短板',
 '涨价',
 '艰难',
 '寒冬',
 '平稳过渡',
 '淡季',
 '故障',
 '杜绝',
 '抑制',
 '偏紧',
 '诉讼',
 '整顿',
 '缩减',
 '冷冻',
 '不良',
 '恶劣',
 '下调',
 '收窄',
 '认缴',
 '减缓',
 '不明朗',
 '削减',
 '投诉',
 '困扰',
 '停运',
 '中低端',
 '减持',
 '抵御',
 '不良贷款',
 '障碍',
 '收缩',
 '减产',
 '违规',
 '伤人',
 '限贷',
 '限价',
 '偏差',
 '触底',
 '减产',
 '负面影响',
 '紧缺',
 '破产',
 '供需矛盾',
 '趋紧',
 '较弱',
 '风暴',
 '不容乐观',
 '减量',
 '跌价',
 '金融危机',
 '倒逼',
 '严酷',
 '减速',
 '减幅',
 '质量事故',
 '失败',
 '劣势',
 '受阻',
 '恶化',
 '逆境',
 '跌幅',
 '偏低',
 '极限',
 '参差不齐',
 '清欠',
 '老旧',
 '']

## 2. 读取data/txts文本中的文本text

In [8]:
# 读取单个文件
text = open('datanew/txts/联美控股2017.txt', encoding='gbk').read()
print(text[:50])

报告期内，公司实现营业收入 2,376,375,380.44 元，同比增长 16.24%，营业利润

In [6]:
# 读取批量文件
# 从 pathlib 模块中导入 Path 类
# Path 的好处是操作路径更优雅、更跨平台（比 os.path 更现代）
from pathlib import Path

# 获取当前工作目录（cwd），并拼接上 datanew/txts，得到文本所在的目录
# Path().cwd() == 当前 Jupyter Notebook 所在的文件夹
# .joinpath('datanew','txts') 表示在当前路径下找到 datanew/txts 这个目录
txtdir = Path().cwd().joinpath('datanew', 'txts')

# 一个列表，用来保存每条记录
records = []

# 遍历 txtdir 目录下所有以 .txt 结尾的文件（模式匹配）
# txtdir.glob('*.txt') 返回一个生成器，每次产出一个 Path 文件对象
for file in txtdir.glob('*.txt'):

    # 将 Path 对象转成字符串路径，便于后续 open() 使用
    file = str(file)

    # 打开该 txt 文件，使用 gbk 编码读取全部内容，并保存到 text
    # 很多公司年报、旧文本使用 gbk，所以这里选用 gbk
    text = open(file, encoding='gbk').read()

    # file.split('/')[-1]：取出路径中的文件名，例如 "联美控股2017.txt"
    # [:-4] 去掉最后 4 个字符，即 ".txt"，只保留 "联美控股2017"
    raw = file.split('\\')[-1][:-4]

    # raw[:-4] → 除去最后四个字符，保留前面部分作为“公司名称”
    # 例如 raw = "联美控股2017"
    # raw[:-4] = "联美控股"
    name = raw[:-4]

    # raw[-4:] → 最后 4 个字符作为年份
    # raw[-4:] = "2017"
    year = raw[-4:]

    records.append({
        "name": name,
        "year": year,
        "text": text
    })

# 查看前3条
records[:3]

[{'name': '三孚股份',
  'year': '2017',
  'text': '2017 年，我国经济坚持以供给侧结构性改革为主线，统筹推进稳增长、促改革、调结构、惠\n\n民生、防风险各项工作，经济运行稳中有进、稳中向好，经济社会保持平稳健康发展。全年石油\n\n和化工行业产品生产整体平稳、经济效益增速加快、对外贸易进一步扩大、结构调整持续优化。\n\n根据国家工业和信息化部数据显示，截至 2017 年末，化工行业主营业务收入 9.10 万亿元，增长\n\n13.8%；全年实现利润 6,072.4 亿元，增长 39.7%。\n\n在此背景下，公司集中力量发展主营业务，不断完善精细化管理体系，各部门紧密配合，全\n\n体员工同心协力，创造了较好的经济效益。全年实现营业收入 107,416.64 万元，较上年同期增长35.67 %，归属于上市公司股东的扣除非经常性损益后的净利润 13,666.95 万元，较上年同期增长\n\n117%。公司围绕循环经济体系核心，积极谋划技术创新，加大研发力度，不断向上下游探索产业\n\n链条的延伸。高纯四氯化硅项目、硫酸钾项目、目前在建的电子级二氯二氢硅及电子级三氯氢硅\n\n项目的逐步开展和实施，使得公司整体产业结构更为优化，技术优势、成本优势得到进一步发挥，\n\n核心竞争力不断增强。\n\n一、硅系列产品\n\n（一）三氯氢硅产品\n\n\u3000\u3000三氯氢硅产品是公司主要产品之一，且是公司目前硅系列产品中的核心产品，其本身可作为电子级二氯二氢硅及电子级三氯氢硅产品的原材料，其副产品普通四氯化硅可作为高纯四氯化硅产品的原材料，物料通过公司内部管道流转，在保证原材料供应及时性的同时，节省了运输等相关费用，有效降低了硅系列产品的生产成本。2017 年三氯氢硅产品生产稳定高效，较好的完成了年度生产目标。\n\n截至 2017 年底，国内在产多晶硅企业 22 家，有效产能共计 27.6 万吨/年，同比增加 31.4%，\n\n全年国内多晶硅产量达到 24 万吨，同比增加 23.1%（数据来源：中国新能源网），多晶硅产品产量的增长使得对三氯氢硅产品的需求相应增加。受原材料价格和下游需求影响，三氯氢硅产品价格 2017 年整体呈上升趋势，公司紧抓市场机遇，与客户积极沟通，保持了良好的合作关系，全年销售业绩喜人，实现销售收入 43,292.90 万元，同比增加 28.10%。\n\n（二）高纯四氯化硅产品\n\n\u3000\u3000高纯四氯化硅产品是公司募投项目产品之一，目前年产能 1 万吨/年。2017 年，通过生产、销售等部门的不懈努力，高纯四氯化硅产品逐步得到了市场的认可，全年销量 4,272.72 吨，实现销售收入 2,702.29 万元。\n\n\u3000\u3000高纯四氯化硅主要应用于光纤预制棒制造行业。随着近年来我国信息化产业的高速发展，对光纤光缆的需求不断增加，从而对光纤预制棒的需求不断增加。高纯四氯化硅产品作为光纤预制棒的主要原材料之一，需求呈逐年上涨的趋势。公司作为国内为数不多的规模化生产高纯四氯化硅产品的企业，产品能够成功走向市场为公司科技创新、寻求产业转型打下了良好的基础。\n\n\u3000\u3000目前，长飞光纤光缆、中天科技、烽火通信等多家国内一流的光纤预制棒生产企业均与公司建立了较为稳定的合作关系。公司也将进一步开拓市场，争取使更多国内外光纤预制棒的生产企业能够了解、认可公司的产品。\n\n（三）电子级二氯二氢硅及电子级三氯氢硅项目\n\n年产 500 吨电子级二氯二氢硅产品和年产 1,000 吨电子级三氯氢硅项目是公司经过较长时间\n\n技术、人才储备后决定实施的具有较高技术含量的项目。电子级二氯二氢硅及电子级三氯氢硅属\n\n于电子气体中的两种，主要应用于硅外延片的生产领域，是半导体行业的重要辅助材料。目前我\n国电子气体产业仍处于发展的初级阶段，总体产业规模较小，而此时中国半导体产业正面临着前\n\n所未有的发展机遇，作为原材料的电子气体行业无疑迎来了很大的发展空间。\n\n公司具有多年硅化合物研发、生产、管理经验，高纯四氯化硅产品成功走向市场，为公司开\n\n发电子级产品打下了良好的基础。目前该项目处于在建状态，项目组正在积极推进项目稳步进行。\n\n未来电子气体项目的建成投产，将使公司产业结构进一步优化，高端产品比例进一步提高，企业\n\n竞争力进一步增强。\n\n二、钾系列产品\n\n（一）氢氧化钾产品\n\n氢氧化钾产品是公司主要产品之一，其副产品氯化氢是三氯氢硅产品主要原材料之一。2017\n\n年公司氢氧化钾产品生产、销售情况正常平稳，实现销售收入 34,330.44 万元。公司加强产品质\n\n量管控，及时了解客户需要，形成了较为稳定的客户群体，河北辛集化工、山东国邦药业、金能\n\n科技、亚邦股份等多家国内外知名企业均与公司保持了长年的良好合作关系。\n\n（二）硫酸钾产品\n\n硫酸钾产品是公司募投项目之一，产能 10 万吨每年。硫酸钾项目的实施，使得公司循环经济\n\n体系得以进一步完善。2017 年硫酸钾生产情况正常，实现销售收入 19,606.93 万元，目前已与金\n\n正大、华鲁恒升、中-阿化肥等多家国内国际复合肥生产企业建立了稳定的合作关系。\n\n\n'},
 {'name': '三棵树',
  'year': '2017',
  'text': '2017 年，全球经济逐步向好，主要发达国家稳定复苏，新兴市场国家强劲增长，中国经济稳\n\n中向好，由高速增长阶段转向高质量发展阶段，经济结构出现重大变革，优化亮点频现。国内经\n\n济正处在转变发展方式、优化经济结构、转换增长动力的攻关期。2017 年三棵树紧跟新时代及新\n\n经济的发展趋势，根据国家产业政策及国内外宏观经济的变化，坚持绿色创新、效能升级、共创\n\n共享三大方向，大力推进战略、文化、品牌、管理、营销、制造等全方位的创新变革，发布了公\n\n司 2018-2022 年发展战略规划，并对公司企业文化进行升级，持续不断向以用户为中心，服务型\n\n制造及高质量发展方向转型，并取得了较为可喜的成绩，规模效益初现，显示了很强的增长后劲。\n\n转型成果主要体现在以下几个方面：\n\n\u3000\u3000（一）拓展和丰富产品线、优化“健康+”产品标准\n\u3000\u3000公司进一步完善“产品一站式”、“涂装一体化”的产品服务体系，不断补齐产品线，丰富相关辅料、辅材产品，提升消费者产品一站式购物体验；不断培育战略新型产品，包括高性能涂料（墙清霾净涂料、热反射隔热涂料等）、瓷砖胶等产品，以满足消费者多层次、全方位的消费需求。同时，公司将进一步升级“健康+”产品标准，使产品健康性能继续保持行业领先地位。通过不断提高产品性能与健康标准，建立竞争门槛，强化“健康漆”领导品牌地位。\n\n（二）积极推进“马上住”、“O2O”及工程涂装服务体系报告期内，积极推进“马上住”服务和“O2O”体系，构建工程涂装平台，布局涂装一体化和\n\n城市焕新重涂业务，打造 361°服务体系，持续推动公司由单一涂料生产商向“涂料+服务咨询+\n\n施工服务”的综合服务商的转变。\n\n\u3000\u3000公司以全资子公司三棵树装饰为主体，利用产品技术及下游地产客户优势，构建工程涂装平台，整合涂装施工资源，扩展服务外延，建立标准化施工模式，形成工程涂装一体化竞争优势。\n\n\u3000\u3000同时，公司进一步优化和提升“马上住”服务体系，加快市场推广速度，增强技术服务团队力量，扩展服务项目和品类，不断提高客户满意度，增强经销商盈利能力；同时，公司进行电商平台改造，全面推进“O2O”模式，通过京东、天猫等网上商城与公司在全国一万多个销售网点进行对接，逐步实现“线上订单，线下配送及服务”销售模式，以节省物流配送成本、缩短服务响应时间，提高电商引流和转化率，进一步提高客户满意度，促进线上线下共同融合发展。\n\n（三）优化和完善渠道管理\n\n\u3000\u3000在家装漆业务方面，公司不断总结和提炼客户盈利经验和经营模式，加强客户与渠道的精细化管理水平，引导和优化现有经销商客户，并根据渠道部署规划大力发展新经销商客户，提升客户与渠道质量，稳步提升“单客、单兵、单店”的效率。截至期末，公司家装漆终端销售网点数量增至 18,730 个。\n\n\u3000\u3000在工程漆业务方面，公司继续加强与大型房地产企业的合作，努力提高市场份额，扩大市场影响力。2017 年 3 月 23 日，公司与广州恒大材料设备有限公司签署《战略合作框架协议》。截至报告期末，公司与国内 10 强地产中的 8 家、50 强地产中的 31 家、100 强地产中的 47 家签署了战略合作协议或建立了合作伙伴关系。并先后荣获“恒大集团 2017 年度卓越战略合作伙伴”、“恒\n\n大集团 2017 年度恒大优秀供应商”、“宝龙地产 2017 年度优秀合作伙伴”、“2017 年中国房地产供应链上市公司综合实力 5 强”、“2017 中国房地产开发企业 500 强首选涂料类品牌”、“工\n\n程建筑涂料影响力品牌”、“2017 年中国房地产金牌供应商”等荣誉称号。（四）品牌建设与推广\n\n\u3000\u3000公司品牌通过事件营销在线上新媒体矩阵及线下活动中进行广度、深度传播，品牌曝光率成绩显著。报告期内，公司通过开展“健康+317 公益日”、“健康+517 健康漆节”、“健康+99 公\n\n益日”、“健康+生态游” 以及“‘马上住’代言人大赛”等活动，积极倡导“健康+”理念，使更多消费者享受“健康家装”，全面推进“健康+”品牌理念的新布局。\n\n（五）进行产能合理布局\n\u3000\u3000公司以大数据管理平台为信息支撑，构建“多、快、好、省”的生态供应链系统。通过公司在全国的四个生产基地及合理的辅料工厂布局，逐步构建多厂多仓全品类供应链网络。采用在生产能力覆盖薄弱地区采取分仓模式，弥补产能布局的不均衡弱点，实现全品类快速供应；同时，公司加强生产线技术改造及配方适应性测试，逐步实现所有生产基地全品类生产的目标，实现产能最优配置，降低物流成本，提高运营效率。报告期内，公司分别与安徽明光经济开发区管理委员会、河北博野县经济开发区管理委员会和莆田市秀屿区人民政府签署了《投资协议书》，规划在明光市、保定市博野县、莆田市秀屿区新建生产基地，提高公司产品的覆盖率和市场占有率，促进产能分布的持续优化。\n\n（六）提高公司信息化管理水平\n\n\u3000\u3000公司持续完善信息化建设，进一步推动移动化管理，完善 OA、“马上住”、BI 等应用的移动化，深化 EHR（人力资源管理系统）的应用，构建 CRM（客户管理系统）、C2M 运营平台，优化运营中心组织架构，建立数据化、智能化、可视化供应链管理平台，降低运营成本，提升精益智能生产管理水平。\n\n\u3000\u3000公司 2017 年度实现营业收入 261,946 万元，较 2016 年度增长 67,125 万元，增长 34.45%，保持良好的增长势头。2017 年度实现利润总额 21,385 万元；净利润 17,597 万元，较 2016 年较上年\n增加 4,232 万元，增长 31.66%。\n\n'},
 {'name': '三江购物',
  'year': '2017',
  'text': '\u3000\u3000报告期内，由于与杭州阿里巴巴泽泰进行战略合作剥离香烟经营业务以及关闭效益不佳门店所致，营业收入同比仍旧下降；公司在网络电商快速发展的背景下，利用品牌优势和经验优势开拓网络零售领域。通过各种方式，丰富公司的销售渠道，扩大销售半径；利用支付宝、微信等第三方支付活动，积极开展各类营销活动、扩大用户的群体，提高门店客流量；内部管理效率不断提升，使归属于上市公司股东的净利润同比持续增长。\n\n现将 2017 年具体经营情况回顾如下：\n\n\u3000\u30001、募集资金情况。截至报告期，公司还有募集资金余额 4566.35 万元（不含利息收入），该资金主要用途为（1）二家创新门店相关费用的支付；（2）一家社区店购房款的余款支付；（3）\n\n之前利用募集资金款开设的连锁门店的后期支付款项；现阶段，本项目按照前期变更后的使用进度正常推进。\n\n\u3000\u30002、增选董事和公司换届工作。2017 年年初完成了公司董事的增选工作，根据公司非公开发行 A 股股票预案及公司与杭州阿里巴巴泽泰签署的股份认购协议，公司董事会将增加两名非独立董事席，经杭州阿里巴巴泽泰提名，董事会提名委员会审核，董事会及股东大会审议通过，徐潘华先生、王曦若女士为公司新增董事。11 月完成了公司第三届董事会的换届工作，经公司第三届董事会第二十二次会议、11 月 8 日召开的 2017 年第一次临时股东大会以及第四届董事会第一次会议，公司进行了换届选举，会议选出了新一届的董事、监事及高级管理人员。\n\n\u3000\u30003、非公开发行进展情况：2017 年 9 月 28 日，中国证券监督管理委员会发行审核委员会对公司非公开发行股票的申请进行了审核，根据会议审核结果，公司本次非公开发行股票的申请获得审核通过。截止到公告日，公司还未收到中国证监会的书面核准文件。\n\n\u3000\u30004、报告期，公司新开业门店 18 家，关闭门店 7 家，整个年净新增店铺数为 11 家，没有完成去年开设“不少于 30 家”新店的计划，门店总数达到 169 家。\n\n\u3000\u3000（1）创新门店，与杭州阿里巴巴泽泰合作使公司开始了全新的业务，从年初“甬江店”以来，公司在经营中不断改善与探索，特别深受中高层消费者的青睐。\n\n（2）小业态店\n\n\u3000\u3000邻里店，公司从“做顾客满意超市”角度出发，对不同顾客群体的购物和需求进行分析研究，满足对便利、消费体验等有更高要求的群体，使之更便捷、更暧心，填补消费空隙。\n\n\u3000\u3000安鲜店，致力打造“安全、新鲜、每一天”的购物体验。结合线下及线上 O2O 综合平台，满足周边 1 公里范围内居民的基本生活需求。\n\n5、改造门店：\n\n\u3000\u3000（1）运用杭州阿里巴巴泽泰新零售的理念，引入可以改造老门店提升存量价值的淘鲜达，在保持线下客流稳定的同时，线上订单也成倍增加，通过门店陈列图编制、生鲜商品标准化工作、门店人员配置标准工作等来提高公司运营的标准化水平，给公司带来较大价值潜力，接下来将快速推进。\n\n\u3000\u3000（2）现有老门店由于大部分开设时间较早，门店生鲜面积较小，且生鲜经营设施设备较匮乏。根据公司社区平价超市的业态特点，为更好地满足顾客需求，对门店布局重新设计，扩大生鲜经营面积，改善门店硬件条件以及购物环境。提高门店的档次和用户对线下购物的体验度。\n\n\u3000\u30006、人才培养与考核。“三江大学”建立后，人员的培训体系逐步完善，对人员的培训得到了很好的加强；建立多方位考核激励体系，对不同岗位的员工起到激励作用，以进一步完善公司管理者的管理水平。为公司发展提供基本的人才需求，保证了公司发展的后劲。\n\u3000\u3000\n\n\u3000\u30007、食品安全。高度重视食品安全工作，不断完善食品安全控制体系，进一步深化食品安全培训工作，开展食品安全专业知识及技能培训、考核，加强员工食品安全意识。积极与当地市场监督管理局协作，开展“省级放心肉菜”项目，对生鲜农产品开展从田地到餐桌的全程追溯，保障蔬菜，肉制品、水产品的全链条管控，实现更为严格的品质管理，为我司搭建了规范化和标准化的农产品质量管理基础。\n\n\u3000\u30008、内控工作。继续按照内部控制要求稳步推进工作，对公司现有制度流程进行全面梳理，进一步完善内部控制体系建设；同时加强日常检查、督促缺陷整改，确保内控实施与评价工作有序进行，保证内控管理工作机制得以长效运行。\n\n'}]

In [7]:
# 也可以这样简化

from pathlib import Path

txtdir = Path().cwd().joinpath('datanew', 'txts')

records = []

for file in txtdir.glob('*.txt'):

    text = file.read_text(encoding='gbk')  # 直接用 Path 的读取

    stem = file.stem              # 文件名，不含后缀，如“三孚股份2017”
    name = stem[:-4]              # 前面的都是公司名
    year = stem[-4:]              # 最后四位是年份

    records.append({
        "name": name,
        "year": year,
        "text": text
    })

records[:1]

[{'name': '三孚股份',
  'year': '2017',
  'text': '2017 年，我国经济坚持以供给侧结构性改革为主线，统筹推进稳增长、促改革、调结构、惠\n\n民生、防风险各项工作，经济运行稳中有进、稳中向好，经济社会保持平稳健康发展。全年石油\n\n和化工行业产品生产整体平稳、经济效益增速加快、对外贸易进一步扩大、结构调整持续优化。\n\n根据国家工业和信息化部数据显示，截至 2017 年末，化工行业主营业务收入 9.10 万亿元，增长\n\n13.8%；全年实现利润 6,072.4 亿元，增长 39.7%。\n\n在此背景下，公司集中力量发展主营业务，不断完善精细化管理体系，各部门紧密配合，全\n\n体员工同心协力，创造了较好的经济效益。全年实现营业收入 107,416.64 万元，较上年同期增长35.67 %，归属于上市公司股东的扣除非经常性损益后的净利润 13,666.95 万元，较上年同期增长\n\n117%。公司围绕循环经济体系核心，积极谋划技术创新，加大研发力度，不断向上下游探索产业\n\n链条的延伸。高纯四氯化硅项目、硫酸钾项目、目前在建的电子级二氯二氢硅及电子级三氯氢硅\n\n项目的逐步开展和实施，使得公司整体产业结构更为优化，技术优势、成本优势得到进一步发挥，\n\n核心竞争力不断增强。\n\n一、硅系列产品\n\n（一）三氯氢硅产品\n\n\u3000\u3000三氯氢硅产品是公司主要产品之一，且是公司目前硅系列产品中的核心产品，其本身可作为电子级二氯二氢硅及电子级三氯氢硅产品的原材料，其副产品普通四氯化硅可作为高纯四氯化硅产品的原材料，物料通过公司内部管道流转，在保证原材料供应及时性的同时，节省了运输等相关费用，有效降低了硅系列产品的生产成本。2017 年三氯氢硅产品生产稳定高效，较好的完成了年度生产目标。\n\n截至 2017 年底，国内在产多晶硅企业 22 家，有效产能共计 27.6 万吨/年，同比增加 31.4%，\n\n全年国内多晶硅产量达到 24 万吨，同比增加 23.1%（数据来源：中国新能源网），多晶硅产品产量的增长使得对三氯氢硅产品的需求相应增加。受原材料价格和下游需求影响，三氯氢硅产品价格 2017 年整体呈上升趋势，公司紧抓市场机遇，与客户积极沟通，保持了良好的合作关系，全年销售业绩喜人，实现销售收入 43,292.90 万元，同比增加 28.10%。\n\n（二）高纯四氯化硅产品\n\n\u3000\u3000高纯四氯化硅产品是公司募投项目产品之一，目前年产能 1 万吨/年。2017 年，通过生产、销售等部门的不懈努力，高纯四氯化硅产品逐步得到了市场的认可，全年销量 4,272.72 吨，实现销售收入 2,702.29 万元。\n\n\u3000\u3000高纯四氯化硅主要应用于光纤预制棒制造行业。随着近年来我国信息化产业的高速发展，对光纤光缆的需求不断增加，从而对光纤预制棒的需求不断增加。高纯四氯化硅产品作为光纤预制棒的主要原材料之一，需求呈逐年上涨的趋势。公司作为国内为数不多的规模化生产高纯四氯化硅产品的企业，产品能够成功走向市场为公司科技创新、寻求产业转型打下了良好的基础。\n\n\u3000\u3000目前，长飞光纤光缆、中天科技、烽火通信等多家国内一流的光纤预制棒生产企业均与公司建立了较为稳定的合作关系。公司也将进一步开拓市场，争取使更多国内外光纤预制棒的生产企业能够了解、认可公司的产品。\n\n（三）电子级二氯二氢硅及电子级三氯氢硅项目\n\n年产 500 吨电子级二氯二氢硅产品和年产 1,000 吨电子级三氯氢硅项目是公司经过较长时间\n\n技术、人才储备后决定实施的具有较高技术含量的项目。电子级二氯二氢硅及电子级三氯氢硅属\n\n于电子气体中的两种，主要应用于硅外延片的生产领域，是半导体行业的重要辅助材料。目前我\n国电子气体产业仍处于发展的初级阶段，总体产业规模较小，而此时中国半导体产业正面临着前\n\n所未有的发展机遇，作为原材料的电子气体行业无疑迎来了很大的发展空间。\n\n公司具有多年硅化合物研发、生产、管理经验，高纯四氯化硅产品成功走向市场，为公司开\n\n发电子级产品打下了良好的基础。目前该项目处于在建状态，项目组正在积极推进项目稳步进行。\n\n未来电子气体项目的建成投产，将使公司产业结构进一步优化，高端产品比例进一步提高，企业\n\n竞争力进一步增强。\n\n二、钾系列产品\n\n（一）氢氧化钾产品\n\n氢氧化钾产品是公司主要产品之一，其副产品氯化氢是三氯氢硅产品主要原材料之一。2017\n\n年公司氢氧化钾产品生产、销售情况正常平稳，实现销售收入 34,330.44 万元。公司加强产品质\n\n量管控，及时了解客户需要，形成了较为稳定的客户群体，河北辛集化工、山东国邦药业、金能\n\n科技、亚邦股份等多家国内外知名企业均与公司保持了长年的良好合作关系。\n\n（二）硫酸钾产品\n\n硫酸钾产品是公司募投项目之一，产能 10 万吨每年。硫酸钾项目的实施，使得公司循环经济\n\n体系得以进一步完善。2017 年硫酸钾生产情况正常，实现销售收入 19,606.93 万元，目前已与金\n\n正大、华鲁恒升、中-阿化肥等多家国内国际复合肥生产企业建立了稳定的合作关系。\n\n\n'}]

## 3. 定义计算情感的函数senti

In [10]:
# 导入 jieba 用于中文分词
import jieba

# 定义情感分析函数 senti()
def senti(text):
    # 初始化正向词和负向词的计数器
    pos_num = 0
    neg_num = 0

    # 对文本进行中文分词，返回一个词语列表
    words = jieba.lcut(text)

    # 遍历分词列表中的每一个词语
    for word in words:

        # 如果该词在正向词典中，则正向计数 +1
        if word in poss:
            pos_num = pos_num + 1

        # 如果该词在负向词典中，则负向计数 +1
        if word in negs:
            neg_num = neg_num + 1

    # 将统计结果以字典的结构返回
    return {"pos": pos_num, "neg": neg_num}

# 查看某份年报的情绪得分
senti(text)

{'pos': 45, 'neg': 4}

In [14]:
# 计算情绪得分
import pandas as pd

df = pd.DataFrame(records)
df[['pos','neg']] = df['text'].apply(lambda x: pd.Series(senti(x)))

In [15]:
df
# 可以看到生成了两列新的情绪得分

      name  year                                               text  pos  neg
0     三孚股份  2017  2017 年，我国经济坚持以供给侧结构性改革为主线，统筹推进稳增长、促改革、调结构、惠\n\...  121    8
1      三棵树  2017  2017 年，全球经济逐步向好，主要发达国家稳定复苏，新兴市场国家强劲增长，中国经济稳\n\...  150   12
2     三江购物  2017  　　报告期内，由于与杭州阿里巴巴泽泰进行战略合作剥离香烟经营业务以及关闭效益不佳门店所致，营...   55    8
3     上海九百  2017  　　2017 年，在国际经济形势依然复杂严峻、国内经济逐步向好的大背景下，面对市场竞争带来的...   89   36
4     上海机电  2017  　　2017 年，房地产行业走势趋于复杂，不同地区差异显著。国家房产调控全面升级，已基本覆盖...   96   23
..     ...   ...                                                ...  ...  ...
495  黑牡丹股份  2014  第四节\t董事会报告\n\n一、董事会关于公司报告期内经营情况的讨论与分析\n\n　　201...  110   27
496  黑牡丹股份  2015  第三节\t公司业务概要\n\n一、 报告期内公司所从事的主要业务、经营模式及行业情况说明\n...  205   57
497  黑牡丹股份  2016  第三节\t公司业务概要\n\n一、 报告期内公司所从事的主要业务、经营模式及行业情况说明\n...  184   55
498  黑牡丹股份  2017  第三节\t公司业务概要\n\n一、 报告期内公司所从事的主要业务、经营模式及行业情况说明\n...  261   56
499   龙建股份  2017  　　报告期内，公司新增合同订单 127 个项目，合同金额 143.76 亿元。黑龙江省内，充...  102    7

[500 rows x 5 columns]

In [17]:
# 查看2017 年负向情绪最高的公司
df_2017.sort_values('neg', ascending=False).head()

     name  year                                               text  pos  neg
329  洛阳钼业  2017  董事长信函\n\n\n\n尊敬的各位股东：\n\n\n\n　　随着全球大宗商品的复苏，得益于...  247  139
49   中国交建  2017  尊敬的各位股东：\n\n2017 年,公司系统谋划，精准发力，抢抓市场机遇，抢占产业制高点，...  329  111
137  华远地产  2017  　　　截至报告期末公司已开发及待开发项目主要分布于北京、西安、长沙、天津、广州和重庆等城市，...  127   86
96   光大银行  2017  2017 年是意义非凡的一年，国家迈入了中国特色社会主义新时\n\n代。国民经济稳中向好，经...  330   86
233  建设银行  2017  各位股东：\n\n　　　2017年，我回到阔别已久的建设银行，携手全行同事，把握中国经济转型...  348   85

In [18]:
# 查看2017年的平均情绪
df_2017[['pos','neg']].mean()

pos    117.990909
neg     23.677273
dtype: float64

## 4. 新建csv，将计算结果存储到csv中

In [19]:
# 创建输出目录
import os
os.makedirs('datanew/output', exist_ok=True)

# 输出路径
output_path = 'datanew/output/情绪分析结果.csv'

# 保存 CSV 文件
df.to_csv(output_path, index=False, encoding='utf-8-sig')

print("已保存到：", output_path)

已保存到： datanew/output/情绪分析结果.csv

---

# ✅ 1. **“文本情感分析（词典法）”提示词（Prompt 模板）**

这些提示词是专门给学生或 ChatGPT 使用的，用于指导完成整个流程。

---

## **📌 提示词 1：读取情感词典**

> **请帮我读取 data/dict 目录下的中文情感词典，将正向词典 positive.txt 与负向词典 negative.txt 分别读入 Python，并转换成列表或 set，并输出词典长度。**

---

## **📌 提示词 2：读取单个文本文件**

> **请读取 data/txts 目录下的某一个文本（例如 “联美控股2017.txt”），使用正确的编码方式（如 gbk）加载全文，并打印前 50 个字符用于检查是否成功读取。**

---

## **📌 提示词 3：定义情感分析函数 senti()**

> **请根据自定义词典法，定义一个函数 senti(text)，其功能是：对输入文本进行分词，统计正向词与负向词在文本中出现的次数，并返回 {'pos': X, 'neg': Y} 这样的结果。**

---

## **📌 提示词 4：测试情感得分**

> **请将 senti() 函数应用于某一个文本 text，并输出正向词数量与负向词数量，用于检查情感函数是否正常。**

---

## **📌 提示词 5：保存情绪得分到 CSV**

> **请将所有文件的 name、year、text、pos、neg 保存为一个 DataFrame，并导出为 datanew/output/情感分析结果.csv，使用 utf-8-sig 编码以便 Excel 打开不乱码。**

---

# 🎯 2. **单文本文件练习题（适合课堂练习）**

这些是学生只需要处理一个文本文件的练习题，非常适合作为“课后练习”或“课堂教学练习”。

---

# 📝 **单文本练习题 A：读取与检查文本**

**题目：**
读取 `data/txts/联美控股2017.txt` 文件，并：

1. 使用合适的编码方式读取全文
2. 打印全文前 50 个字符
3. 打印全文的总字符数

**示例输出：**

```
2017 年，面对复杂的外部环境……
文本长度： 15234
```

---

# 📝 **单文本练习题 B：读取情感词典**

**题目：**

1. 读取 `data/dict/positive.txt` 与 `data/dict/negative.txt`
2. 打印正向词数量
3. 打印负向词数量
4. 随机打印 10 个词查看是否读取成功

---

# 📝 **单文本练习题 C：完成 senti(text) 函数**

**题目：**
根据自定义词典，完成一个函数 `senti(text)`，要求：

* 使用 jieba 进行分词
* 遍历每个词
* 统计 `pos`、`neg`
* 返回字典结果

**验证任务：**
调用：

```python
senti("我今天非常高兴，但有点担心。")
```

并查看输出是否符合你的预期。

---

# 📝 **单文本练习题 D：计算单个文本情绪得分**

**题目：**

1. 对 `联美控股2017.txt` 执行 sentiment analysis
2. 输出：

```
正向词数量：?
负向词数量：?
情绪净值（pos - neg）：?
```

---

# 📝 **单文本练习题 E：结果解释题**

**题目：**

假设你得到了以下结果：

```
{"pos": 45, "neg": 4}
```

请用你自己的话解释：

1. 该年报整体情绪是偏正向、偏负向还是中性？
2. 为什么这种“词典计数法”可能会忽略某些细微语义？

---

---

## 📝 练习 A 答案：读取与检查文本

**题目回顾：**

> 读取 `data/txts/联美控股2017.txt`，
> 1）用正确编码读取全文
> 2）打印前 50 个字符
> 3）打印总字符数

**参考答案代码：**

```python
# 练习 A 答案

file = 'datanew/txts/联美控股2017.txt'

# 1. 读取全文（很多年报是 gbk 编码）
with open(file, encoding='gbk') as f:
    text = f.read()

# 2. 打印前 50 个字符
print("文本前 50 个字符：")
print(text[:50])

# 3. 打印总字符数
print("\n文本总字符数：", len(text))
```

---

## 📝 练习 B 答案：读取情感词典

**题目回顾：**

> 1）读取 `data/dict/positive.txt`、`negative.txt`
> 2）打印正向词数量
> 3）打印负向词数量
> 4）随机打印 10 个词

**参考答案代码：**

```python
# 练习 B 答案

import random

# 1. 读取正向词典
with open('datanew/dict/positive.txt', encoding='gbk') as f:
    poss = [w.strip() for w in f if w.strip()]

# 2. 读取负向词典
with open('datanew/dict/negative.txt', encoding='gbk') as f:
    negs = [w.strip() for w in f if w.strip()]

# 3. 打印数量
print("正向词数量：", len(poss))
print("负向词数量：", len(negs))

# 4. 随机打印 10 个词（如果词典长度不足 10，会自动取全部）
print("\n随机 10 个正向词：", random.sample(poss, k=min(10, len(poss))))
print("\n随机 10 个负向词：", random.sample(negs, k=min(10, len(negs))))
```

---

## 📝 练习 C 答案：完成 `senti(text)` 函数

**题目回顾：**

> 用自定义词典，完成 `senti(text)`：
>
> * jieba 分词
> * 统计 pos、neg
> * 返回 `{'pos': X, 'neg': Y}`
>   并测试：
>   `senti("我今天非常高兴，但有点担心。")`

**参考答案代码：**

```python
# 练习 C 答案

import jieba

# 假设 poss, negs 已经在练习 B 中读好了
# poss / negs 是列表，转成 set 查找更快
pos_set = set(poss)
neg_set = set(negs)

def senti(text):
    """
    输入：一段中文文本（字符串）
    输出：字典 {'pos': 正向词个数, 'neg': 负向词个数}
    """
    pos_num = 0
    neg_num = 0

    # jieba 分词
    words = jieba.lcut(text)

    # 遍历每一个词
    for w in words:
        if w in pos_set:
            pos_num += 1
        if w in neg_set:
            neg_num += 1

    return {"pos": pos_num, "neg": neg_num}

# 测试
test_text = "我今天非常高兴，但有点担心。"
print("测试句子：", test_text)
print("情绪统计结果：", senti(test_text))
```

> 实际输出取决于你的词典里有没有“高兴”“担心”等词。
> 格式会类似：`{'pos': 1, 'neg': 1}` 或 `{'pos': 1, 'neg': 0}`。

---

## 📝 练习 D 答案：计算单个年报的情绪得分

**题目回顾：**

> 对 `联美控股2017.txt` 执行情感分析，输出：
>
> * 正向词数量
> * 负向词数量
> * 情绪净值（pos - neg）

**参考答案代码：**

```python
# 练习 D 答案

file = 'data/txts/联美控股2017.txt'

# 读取文本
with open(file, encoding='gbk') as f:
    text = f.read()

# 使用前面定义好的 senti() 函数
result = senti(text)

pos_num = result['pos']
neg_num = result['neg']
net_score = pos_num - neg_num

print("联美控股 2017 年报情绪分析：")
print("正向词数量：", pos_num)
print("负向词数量：", neg_num)
print("情绪净值（pos - neg）：", net_score)
```

> ⚠ 注意：这里的具体数字完全取决于你本地的文本 + 词典内容，
> 所以数字要让学生自己跑，不适合在答案里写死。

---

## 📝 练习 E 答案：解释情绪结果

**题目回顾：**

> 已知结果：
> `{"pos": 45, "neg": 4}`
> 问：
> 1）整体情绪偏正向 / 负向 / 中性？
> 2）这种“词典计数法”可能忽略什么？

**参考答案（文字版）：**

1. 由于正向词数量远大于负向词数量（45 vs 4），
   👉 可以认为：**该文本整体情绪明显偏正向、语气较为乐观**。
   在年报场景中，可以解读为：公司在报告期内整体表达的是“积极、成长、向好”的语气。

2. 词典计数法可能忽略的地方包括：

   * **语境问题**：
     “风险可控”“降低亏损”“避免失败”中可能包含负面词（风险、亏损、失败），
     但整体表达的是“控制、改善”，并不是真正的负面情绪。
   * **否定词问题**：
     “并不悲观”“不是失败”中含有负面词，但前面有“不是”“不”，实际语气可能偏中性或正向。
   * **反讽与隐晦表达**：
     例如：“真是优秀得让人无话可说”，可能是反话，词典很难识别。
   * **词典覆盖问题**：
     新词、行业术语、网络用语（“爆雷”“踩雷”“躺平”等）如果不在词典里，会被完全忽略。

> **词典法优点是简单透明、容易实现；缺点是“不会理解语境”，容易被否定句、反讽、隐含语气骗到。**

---

## 有更简单直接的中文情感分析库：中文情感分析库cnsenti
https://github.com/hidadeng/cnsenti

In [2]:
from cnsenti import Sentiment

senti = Sentiment()
test_text= '我好开心啊，非常非常非常高兴！今天我得了一百分，我很兴奋开心，愉快，开心'
result = senti.sentiment_count(test_text)
print(result)

{'words': 22, 'sentences': 2, 'pos': 4, 'neg': 0}

In [3]:
from cnsenti import Emotion

emotion = Emotion()
test_text = '我好开心啊，非常非常非常高兴！今天我得了一百分，我很兴奋开心，愉快，开心'
result = emotion.emotion_count(test_text)
print(result)

{'words': 22, 'sentences': 2, '好': 0, '乐': 4, '哀': 0, '怒': 0, '惧': 0, '恶': 0, '惊': 0}

---

# 🎯 **sentiment 和 emotion de 核心差异总结**

### ✔ `Sentiment` —— 二分类情感分析（正向 / 负向）

### ✔ `Emotion` —— 多类别情绪识别（快乐 / 愤怒 / 悲伤 / 恐惧 / 惊讶 / 厌恶）

它们来自 **同一个库 cnsenti**，但功能完全不同。

---

# 🟢 1. `Sentiment`：正负情感分析（情感极性）

适合：

* 判断文本整体是 “positive” 还是 “negative”
* 例如你做的年报情绪分析
* 内容越长、越正式的文本越适用

**代码：**

```python
from cnsenti import Sentiment
senti = Sentiment()
result = senti.sentiment_count(text)
```

得到结果结构大概是：

```python
{'pos': 12, 'neg': 2}
```

🔍 意思是：

* 出现了 12 个正向词
* 出现了 2 个负向词
* 文本整体偏正向

👉 **这是和你自定义词典法最接近的分析方式**。

---

# 🟣 2. `Emotion`：六大情绪分类（心理学情绪）

适合：

* 短文本、社交媒体、评论、微博、情绪表达明确的内容
* 更“人类情绪感受”方向

```python
from cnsenti import Emotion
emotion = Emotion()
result = emotion.emotion_count(text)
```

结果类似：

```python
{
 'happy': 10,   # 高兴
 'fear': 0,     # 恐惧
 'anger': 0,    # 生气
 'sad': 0,      # 悲伤
 'surprise': 1, # 惊讶
 'disgust': 0   # 厌恶
}
```

🔍 它不是判断“正负”，而是判断属于哪种“情绪类别”。

---