## 选取行
|方法|功能|
|:---|:---|
|df.head(n)|前n行|
|df.tail(n)|后n行|
|df.sample(n)|随机抽n行|
|df.sample(frac)|按frac比例抽取|
|df.nlargest(n, columns)|选出columns最大的前n行|
|df.nsmallest(n, columns)|选出columns最小的前n行|
|``df[df['A']==5]``|将字段A等于5的所有的数据显示出来|
|``df.loc[indexs, columns]``|选择指定行列的数据|

In [1]:
import pandas as pd

df = pd.read_csv('iris.csv')
df

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [2]:
#字段的数据类型
df.dtypes

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species          object
dtype: object

In [3]:
#df有多少条数据
len(df)

150

In [4]:
#前n个
df.head(10)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [5]:
#默认前5行
df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
#后n个
df.tail()

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [7]:
#随机抽取n个
df.sample(10)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
59            5.2          2.7           3.9          1.4  versicolor
133           6.3          2.8           5.1          1.5   virginica
41            4.5          2.3           1.3          0.3      setosa
9             4.9          3.1           1.5          0.1      setosa
129           7.2          3.0           5.8          1.6   virginica
26            5.0          3.4           1.6          0.4      setosa
136           6.3          3.4           5.6          2.4   virginica
109           7.2          3.6           6.1          2.5   virginica
124           6.7          3.3           5.7          2.1   virginica
87            6.3          2.3           4.4          1.3  versicolor

In [8]:
#随机抽1个
df.sample()

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
30           4.8          3.1           1.6          0.2  setosa

In [9]:
#按照比例随机抽取
df.sample(frac=0.1)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
147           6.5          3.0           5.2          2.0   virginica
140           6.7          3.1           5.6          2.4   virginica
115           6.4          3.2           5.3          2.3   virginica
27            5.2          3.5           1.5          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
95            5.7          3.0           4.2          1.2  versicolor
96            5.7          2.9           4.2          1.3  versicolor
113           5.7          2.5           5.0          2.0   virginica
77            6.7          3.0           5.0          1.7  versicolor
78            6.0          2.9           4.5          1.5  versicolor
106           4.9          2.5           4.5          1.7   virginica
136           6.3          3.4           5.6          2.4   virginica
54            6.5          2.8           4.6          1.5  versicolor
0             5.1          3.5           1.4          0.2      setosa
43            5.0          3.5           1.6          0.6      setosa

In [10]:
#按照某个字段，选取最大的前n个
df.nlargest(10, 'Sepal.Length')

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
131           7.9          3.8           6.4          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
105           7.6          3.0           6.6          2.1  virginica
130           7.4          2.8           6.1          1.9  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
125           7.2          3.2           6.0          1.8  virginica

In [11]:
#按照某个字段，选取最小的前n个
df.nlargest(10, 'Sepal.Length')

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
131           7.9          3.8           6.4          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
105           7.6          3.0           6.6          2.1  virginica
130           7.4          2.8           6.1          1.9  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
125           7.2          3.2           6.0          1.8  virginica

In [12]:
#逻辑条件
df['Sepal.Length']>6

0      False
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149    False
Name: Sepal.Length, Length: 150, dtype: bool

### 逻辑选取
``df[df逻辑条件]``

In [13]:
df[df['Sepal.Length']>6]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
54            6.5          2.8           4.6          1.5  versicolor
56            6.3          3.3           4.7          1.6  versicolor
..            ...          ...           ...          ...         ...
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica

[61 rows x 5 columns]

### df.loc[indexs, columns]
选取指定行列

- indexs可以使切片表达式，逻辑条件，某些情况下可以是字符串日期
- columns表示列相关的信息，一般是字符串或者字符串列表

In [14]:
# 用 .loc 取出第 10~20 行的 Sepal.Width 列
df.loc[10:20, 'Sepal.Width']

10    3.7
11    3.4
12    3.0
13    3.0
14    4.0
15    4.4
16    3.9
17    3.5
18    3.8
19    3.8
20    3.4
Name: Sepal.Width, dtype: float64

In [15]:
#选取某列，返回series
df['Species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object

In [16]:
type(df['Species'])

pandas.core.series.Series

In [17]:
#选取某列，返回series
df.Species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object

In [18]:
#选取某列，返回dataframe
df[['Species']]

       Species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [19]:
type(df[['Species']])

pandas.core.frame.DataFrame

In [20]:
# 选取多列，返回dataframe
df[['Sepal.Length', 'Species']]

     Sepal.Length    Species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]

In [21]:
# df.loc[rows, columns]
df.loc[1:10, ['Sepal.Length', 'Sepal.Width', 'Species']]

    Sepal.Length  Sepal.Width Species
1            4.9          3.0  setosa
2            4.7          3.2  setosa
3            4.6          3.1  setosa
4            5.0          3.6  setosa
5            5.4          3.9  setosa
6            4.6          3.4  setosa
7            5.0          3.4  setosa
8            4.4          2.9  setosa
9            4.9          3.1  setosa
10           5.4          3.7  setosa