|代码|功能|
|:---|:---|
|``df['Species']``|选取Sepecies列，返回series|
|``df.Species``|选取Sepecies列，返回series|
|``df[['Species']]``|选取Sepecies列，返回DataFrame|
|``df[['Sepal.Length', 'Sepal.Width']]``|选取Sepal.Length和Sepal.Width列，返回DataFrame|
|``df.loc[indexs, columns]``|选取indexs和columns所在的行列数据。|

In [4]:
# 读取数据
import pandas as pd

df = pd.read_csv('data/iris.csv')
df

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
#选取某列，返回series
df['Species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object

In [8]:
type(df['Species'])

pandas.core.series.Series

In [9]:
#选取某列，返回series
df.Species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object

In [10]:
#选取某列，返回dataframe
df[['Species']]

       Species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [11]:
type(df[['Species']])

pandas.core.frame.DataFrame

In [12]:
# 选取多列，返回dataframe
df[['Sepal.Length', 'Species']]

     Sepal.Length    Species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]

In [14]:
# df.loc[rows, columns]
df.loc[1:10, ['Sepal.Length', 'Sepal.Width', 'Species']]

    Sepal.Length  Sepal.Width Species
1            4.9          3.0  setosa
2            4.7          3.2  setosa
3            4.6          3.1  setosa
4            5.0          3.6  setosa
5            5.4          3.9  setosa
6            4.6          3.4  setosa
7            5.0          3.4  setosa
8            4.4          2.9  setosa
9            4.9          3.1  setosa
10           5.4          3.7  setosa

In [15]:
df

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [1]:
# 在表中创建新字段
import pandas as pd
data = {'Width': [4,3,4,7,8],        
'Length': [2,2,1,5,2]}
df = pd.DataFrame(data)
df

   Width  Length
0      4       2
1      3       2
2      4       1
3      7       5
4      8       2

In [2]:
# 求Area
df['Area'] = df['Width']*df['Length']
df

   Width  Length  Area
0      4       2     8
1      3       2     6
2      4       1     4
3      7       5    35
4      8       2    16

In [3]:
#新建 Height
df['Height'] = [10, 10, 10, 10, 10]
df

   Width  Length  Area  Height
0      4       2     8      10
1      3       2     6      10
2      4       1     4      10
3      7       5    35      10
4      8       2    16      10

In [4]:
#更新已有字段数据
df['Height2'] = 20
df

   Width  Length  Area  Height  Height2
0      4       2     8      10       20
1      3       2     6      10       20
2      4       1     4      10       20
3      7       5    35      10       20
4      8       2    16      10       20

In [5]:
df['体积'] = df['Area']*df['Height']
df

   Width  Length  Area  Height  Height2   体积
0      4       2     8      10       20   80
1      3       2     6      10       20   60
2      4       1     4      10       20   40
3      7       5    35      10       20  350
4      8       2    16      10       20  160