# 《数据重塑》

（df.sort_values / df.rename / df.set_index / df.sort_index / df.drop）

---

## 1. 为什么要“重塑数据”？

你手里的 DataFrame，就像一屋子的衣服：

* 有的乱七八糟堆着（排序 sort）
* 有的名字实在看不下去（重命名 rename）
* 有的衣柜没有好好贴标签（设置索引 set_index）
* 还可能出现穿搭灾难品（想删掉 drop）

我们今天要做的，就是 **一次温柔的“数据收纳术”** 🧺✨。

---

# 2. sort_values：给乱糟糟的房间排个序

### 直觉理解

sort_values 就像给学生按照成绩排座位：

* 默认从矮 → 高（小 → 大）
* ascending=False 就是从高 → 矮（大 → 小）

### 示例

```python
df3.sort_values('mpg')
```

效果就像：

> “同学们！按油耗从低到高站好！”

如果你想反过来：

```python
df3.sort_values('mpg', ascending=False)
```

> “油耗最高的站前排！”

---

## 3. rename：给列换个更好听、看得懂的名字

### 直觉理解

有些列名像“horsepower”，学生会问你“马力是哪一列？”
你就可以给它改成更贴心的中文名。

### 示例

```python
df.rename(columns={'horsepower': '马力'})
```

> “来！从今天起你叫‘马力’了！”😄

---

## 4. set_index：重新贴标签，让数据更好找

### 直觉理解

索引 index 就像“抽屉上的贴纸”。

* 用姓名来做 index
* 或用成绩、课程做 index

这样查找会更快、看起来也更规范。

### 示例

```python
df.set_index('成绩')
```

效果：

> 把“成绩”变成左边的标签列。

---

## 5. sort_index：按标签的顺序整理抽屉

### 直觉理解

如果 index 是乱的（比如顺序被打乱），
sort_index 就像按顺序重新整理标签。

```python
df.sort_index()
```

---

## 6. drop：温柔地丢掉不要的列/行

### 直觉理解

drop 就像“断舍离”：

* drop(列名, axis=1) → 丢掉列
* drop(行名, axis=0) → 丢掉行

### 示例（丢掉“性别”列）

```python
df.drop('性别', axis=1)
```

---

# 7. 综合情境例子（超甜版）

假设有学生成绩表：

| 姓名    | 课程 | 成绩 | 性别 |
| ----- | -- | -- | -- |
| David | 数学 | 88 | 男  |
| Mary  | 英语 | 89 | 女  |

现在我们进行几步“温柔整理”：

### ✔ 第一步：按成绩排序

```python
df.sort_values('成绩', ascending=False)
```

### ✔ 第二步：给列名换成更规范的英文

```python
df.rename(columns={'成绩': 'score'})
```

### ✔ 第三步：把姓名设为 index

```python
df.set_index('姓名')
```

### ✔ 第四步：如果 index 乱了，再排一下

```python
df.sort_index()
```

### ✔ 第五步：不要展示性别

```python
df.drop('性别', axis=1)
```

这样一套走下来，数据像做了水疗一样焕然一新✨。

---

# 8. 课后小练习（含答案）

## **练习 1：按“horsepower”升序排列 df3**

👉 请写出代码

（答案）

```python
df3.sort_values('horsepower')
```

---

## **练习 2：把 df 中的 “car name” 列改成 “车型”**

👉 写出 rename 语句即可

（答案）

```python
df.rename(columns={'car name': '车型'})
```

---

## **练习 3：把“课程”作为 index，并按 index 排序**

（答案）

```python
df.set_index('课程').sort_index()
```

---

## **练习 4：删除 df 中的 “origin” 列**

（答案）

```python
df.drop('origin', axis=1)
```

---

|函数或方法|功能|
|:---|:---|
|df.sort_values(by)|按照某列by对df进行排序|
|df.rename(columns)|对df的字段名进行重命名|
|df.set_index(keys)|设置df的行索引|
|df.sort_index()|按照行索引对df进行排序|

## df.sort_values(by)
- 可以对某(些)变量进行排序

In [1]:
import pandas as pd
df1 = pd.read_csv('reshape/auto-mpg1.csv')
df1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,15.0,6,258,110,3730,19.0,75,1,amc matador
1,18.0,6,225,95,3785,19.0,75,1,plymouth fury
2,21.0,6,231,110,3039,15.0,75,1,buick skyhawk
3,20.0,8,262,110,3221,13.5,75,1,chevrolet monza 2+2
4,13.0,8,302,129,3169,12.0,75,1,ford mustang ii
...,...,...,...,...,...,...,...,...,...
231,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
232,44.0,4,97,52,2130,24.6,82,2,vw pickup
233,32.0,4,135,84,2295,11.6,82,1,dodge rampage
234,28.0,4,120,79,2625,18.6,82,1,ford ranger
235,31.0,4,119,82,2720,19.4,82,1,chevy s-10

In [2]:
df2 = pd.read_csv('reshape/auto-mpg2.csv')
df2

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
191,22.0,6,225.0,100,3233,15.4,76,1,plymouth valiant
192,22.0,6,250.0,105,3353,14.5,76,1,chevrolet nova
193,24.0,6,200.0,81,3012,17.6,76,1,ford maverick
194,22.5,6,232.0,90,3085,17.6,76,1,amc hornet
195,29.0,4,85.0,52,2035,22.2,76,1,chevrolet chevette

In [3]:
df3 = pd.concat([df1, df2])
df3

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,15.0,6,258.0,110,3730,19.0,75,1,amc matador
1,18.0,6,225.0,95,3785,19.0,75,1,plymouth fury
2,21.0,6,231.0,110,3039,15.0,75,1,buick skyhawk
3,20.0,8,262.0,110,3221,13.5,75,1,chevrolet monza 2+2
4,13.0,8,302.0,129,3169,12.0,75,1,ford mustang ii
...,...,...,...,...,...,...,...,...,...
191,22.0,6,225.0,100,3233,15.4,76,1,plymouth valiant
192,22.0,6,250.0,105,3353,14.5,76,1,chevrolet nova
193,24.0,6,200.0,81,3012,17.6,76,1,ford maverick
194,22.5,6,232.0,90,3085,17.6,76,1,amc hornet
195,29.0,4,85.0,52,2035,22.2,76,1,chevrolet chevette

In [79]:
# 根据mpg排序
df3.sort_values('mpg')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
124,11.0,8,350.0,180,3664,11.0,73,1,oldsmobile omega
103,11.0,8,400.0,150,4997,14.0,73,1,chevrolet impala
...,...,...,...,...,...,...,...,...,...
164,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
232,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
163,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
167,44.6,4,91.0,67,1850,13.8,80,3,honda civic 1500 gl
160,46.6,4,86.0,65,2110,17.9,80,3,mazda glc

In [4]:
# 根据mpg排序，设定排序方向
df3.sort_values('mpg', ascending=False)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
160,46.6,4,86.0,65,2110,17.9,80,3,mazda glc
167,44.6,4,91.0,67,1850,13.8,80,3,honda civic 1500 gl
163,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel)
232,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
164,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
...,...,...,...,...,...,...,...,...,...
27,11.0,8,318.0,210,4382,13.5,70,1,dodge d200
124,11.0,8,350.0,180,3664,11.0,73,1,oldsmobile omega
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d

In [5]:
help(df3.sort_values)

Help on method sort_values in module pandas.core.frame:

sort_values(
    by: 'IndexLabel',
    *,
    axis: 'Axis' = 0,
    ascending: 'bool | list[bool] | tuple[bool, ...]' = True,
    inplace: 'bool' = False,
    kind: 'SortKind' = 'quicksort',
    na_position: 'str' = 'last',
    ignore_index: 'bool' = False,
    key: 'ValueKeyFunc | None' = None
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Sort by the values along either axis.

    Parameters
    ----------
    by : str or list of str
        Name or list of names to sort by.

        - if `axis` is 0 or `'index'` then `by` may contain index
          levels and/or column labels.
        - if `axis` is 1 or `'columns'` then `by` may contain column
          levels and/or index labels.
    axis : "{0 or 'index', 1 or 'columns'}", default 0
         Axis to be sorted.
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
         Choice of sorting algorithm. See also :func:`numpy.sort` for more
         information. `mergesort` and `stable` are the only stable algorithms. For
         DataFrames, this option is only applied when sorting on a single
         column or label.
    na_position : {'first', 'last'}, default 'last'
         Puts NaNs at the beginning if `first`; `last` puts NaNs at the
         end.
    ignore_index : bool, default False
         If True, the resulting axis will be labeled 0, 1, …, n - 1.
    key : callable, optional
        Apply the key function to the values
        before sorting. This is similar to the `key` argument in the
        builtin :meth:`sorted` function, with the notable difference that
        this `key` function should be *vectorized*. It should expect a
        ``Series`` and return a Series with the same shape as the input.
        It will be applied to each column in `by` independently.

    Returns
    -------
    DataFrame or None
        DataFrame with sorted values or None if ``inplace=True``.

    See Also
    --------
    DataFrame.sort_index : Sort a DataFrame by the index.
    Series.sort_values : Similar method for a Series.

    Examples
    --------
    >>> df = pd.DataFrame({
    ...     'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    ...     'col2': [2, 1, 9, 8, 7, 4],
    ...     'col3': [0, 1, 9, 4, 2, 3],
    ...     'col4': ['a', 'B', 'c', 'D', 'e', 'F']
    ... })
    >>> df
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Sort by col1

    >>> df.sort_values(by=['col1'])
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    Sort by multiple columns

    >>> df.sort_values(by=['col1', 'col2'])
      col1  col2  col3 col4
    1    A     1     1    B
    0    A     2     0    a
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    Sort Descending

    >>> df.sort_values(by='col1', ascending=False)
      col1  col2  col3 col4
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B
    3  NaN     8     4    D

    Putting NAs first

    >>> df.sort_values(by='col1', ascending=False, na_position='first')
      col1  col2  col3 col4
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B

    Sorting with a key function

    >>> df.sort_values(by='col4', key=lambda col: col.str.lower())
       col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Natural sort with the key argument,
    using the `natsort <https://github.com/SethMMorton/natsort>` package.

    >>> df = pd.DataFrame({
    ...    "time": ['0hr', '128hr', '72hr', '48hr', '96hr'],
    ...    "value": [10, 20, 30, 40, 50]
    ... })
    >>> df
        time  value
    0    0hr     10
    1  128hr     20
    2   72hr     30
    3   48hr     40
    4   96hr     50
    >>> from natsort import index_natsorted
    >>> df.sort_values(
    ...     by="time",
    ...     key=lambda x: np.argsort(index_natsorted(df["time"]))
    ... )
        time  value
    0    0hr     10
    3   48hr     40
    2   72hr     30
    4   96hr     50
    1  128hr     20

## df.rename(columns)
按照columns字典,对df中的列名进行重命名
- columns 字典，例如columns={'y':'year'} ，将df中的字段名y更改为year

In [6]:
# 将horsepower更改为'马力'； 将cylinders更改为'气缸数'
columns = {'horsepower':'马力',
          'cylinders':'气缸数'}

df3.rename(columns=columns)

,mpg,气缸数,displacement,马力,weight,acceleration,model year,origin,car name
0,15.0,6,258.0,110,3730,19.0,75,1,amc matador
1,18.0,6,225.0,95,3785,19.0,75,1,plymouth fury
2,21.0,6,231.0,110,3039,15.0,75,1,buick skyhawk
3,20.0,8,262.0,110,3221,13.5,75,1,chevrolet monza 2+2
4,13.0,8,302.0,129,3169,12.0,75,1,ford mustang ii
...,...,...,...,...,...,...,...,...,...
191,22.0,6,225.0,100,3233,15.4,76,1,plymouth valiant
192,22.0,6,250.0,105,3353,14.5,76,1,chevrolet nova
193,24.0,6,200.0,81,3012,17.6,76,1,ford maverick
194,22.5,6,232.0,90,3085,17.6,76,1,amc hornet
195,29.0,4,85.0,52,2035,22.2,76,1,chevrolet chevette

In [7]:
help(df3.rename)

Help on method rename in module pandas.core.frame:

rename(
    mapper: 'Renamer | None' = None,
    *,
    index: 'Renamer | None' = None,
    columns: 'Renamer | None' = None,
    axis: 'Axis | None' = None,
    copy: 'bool | None' = None,
    inplace: 'bool' = False,
    level: 'Level | None' = None,
    errors: 'IgnoreRaise' = 'ignore'
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Rename columns or index labels.

    Function / dict values must be unique (1-to-1). Labels not contained in
    a dict / Series will be left as-is. Extra labels listed don't throw an
    error.

    See the :ref:`user guide <basics.rename>` for more.

    Parameters
    ----------
    mapper : dict-like or function
        Dict-like or function transformations to apply to
        that axis' values. Use either ``mapper`` and ``axis`` to
        specify the axis to target with ``mapper``, or ``index`` and
        ``columns``.
    index : dict-like or function
        Alternative to specifying axis (``mapper, axis=0``
        is equivalent to ``index=mapper``).
    columns : dict-like or function
        Alternative to specifying axis (``mapper, axis=1``
        is equivalent to ``columns=mapper``).
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis to target with ``mapper``. Can be either the axis name
        ('index', 'columns') or number (0, 1). The default is 'index'.
    copy : bool, default True
        Also copy underlying data.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
        If True then value of copy is ignored.
    level : int or level name, default None
        In case of a MultiIndex, only rename labels in the specified
        level.
    errors : {'ignore', 'raise'}, default 'ignore'
        If 'raise', raise a `KeyError` when a dict-like `mapper`, `index`,
        or `columns` contains labels that are not present in the Index
        being transformed.
        If 'ignore', existing keys will be renamed and extra keys will be
        ignored.

    Returns
    -------
    DataFrame or None
        DataFrame with the renamed axis labels or None if ``inplace=True``.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis and
        "errors='raise'".

    See Also
    --------
    DataFrame.rename_axis : Set the name of the axis.

    Examples
    --------
    ``DataFrame.rename`` supports two calling conventions

    * ``(index=index_mapper, columns=columns_mapper, ...)``
    * ``(mapper, axis={'index', 'columns'}, ...)``

    We *highly* recommend using keyword arguments to clarify your
    intent.

    Rename columns using a mapping:

    >>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
    >>> df.rename(columns={"A": "a", "B": "c"})
       a  c
    0  1  4
    1  2  5
    2  3  6

    Rename index using a mapping:

    >>> df.rename(index={0: "x", 1: "y", 2: "z"})
       A  B
    x  1  4
    y  2  5
    z  3  6

    Cast index labels to a different type:

    >>> df.index
    RangeIndex(start=0, stop=3, step=1)
    >>> df.rename(index=str).index
    Index(['0', '1', '2'], dtype='object')

    >>> df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")
    Traceback (most recent call last):
    KeyError: ['C'] not found in axis

    Using axis-style parameters:

    >>> df.rename(str.lower, axis='columns')
       a  b
    0  1  4
    1  2  5
    2  3  6

    >>> df.rename({1: 2, 2: 4}, axis='index')
       A  B
    0  1  4
    2  2  5
    4  3  6

## df.sort_index()
按照index对df进行排序

In [8]:
df3.sort_index()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
0,15.0,6,258.0,110,3730,19.0,75,1,amc matador
1,18.0,6,225.0,95,3785,19.0,75,1,plymouth fury
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
...,...,...,...,...,...,...,...,...,...
231,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
232,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
233,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
234,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
235,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

## df.set_index(keys)
将keys设置成行索引。

In [9]:
df = pd.DataFrame({'姓名': ['David', 'David', 'David', 'Mary', 'Mary',
                           'Mary'],
                   '课程': ['语文', '数学', '英语', '语文', '数学', '英语'],
                   '成绩': [98, 88, 79, 93, 97, 89],
                   '性别': ['男', '男', '男', '女', '女', '女']})
df

      姓名  课程  成绩 性别
0  David  语文  98  男
1  David  数学  88  男
2  David  英语  79  男
3   Mary  语文  93  女
4   Mary  数学  97  女
5   Mary  英语  89  女

In [10]:
df.set_index('成绩')

       姓名  课程 性别
成绩
98  David  语文  男
88  David  数学  男
79  David  英语  男
93   Mary  语文  女
97   Mary  数学  女
89   Mary  英语  女

In [11]:
df.set_index('成绩').sort_index(ascending=False)

       姓名  课程 性别
成绩
98  David  语文  男
97   Mary  数学  女
93   Mary  语文  女
89   Mary  英语  女
88  David  数学  男
79  David  英语  男

In [12]:
help(df.sort_index)

Help on method sort_index in module pandas.core.frame:

sort_index(
    *,
    axis: 'Axis' = 0,
    level: 'IndexLabel | None' = None,
    ascending: 'bool | Sequence[bool]' = True,
    inplace: 'bool' = False,
    kind: 'SortKind' = 'quicksort',
    na_position: 'NaPosition' = 'last',
    sort_remaining: 'bool' = True,
    ignore_index: 'bool' = False,
    key: 'IndexKeyFunc | None' = None
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Sort object by labels (along an axis).

    Returns a new DataFrame sorted by label if `inplace` argument is
    ``False``, otherwise updates the original DataFrame and returns None.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        The axis along which to sort.  The value 0 identifies the rows,
        and 1 identifies the columns.
    level : int or level name or list of ints or list of level names
        If not None, sort on values in specified index level(s).
    ascending : bool or list-like of bools, default True
        Sort ascending vs. descending. When the index is a MultiIndex the
        sort direction can be controlled for each level individually.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
        Choice of sorting algorithm. See also :func:`numpy.sort` for more
        information. `mergesort` and `stable` are the only stable algorithms. For
        DataFrames, this option is only applied when sorting on a single
        column or label.
    na_position : {'first', 'last'}, default 'last'
        Puts NaNs at the beginning if `first`; `last` puts NaNs at the end.
        Not implemented for MultiIndex.
    sort_remaining : bool, default True
        If True and sorting by level and index is multilevel, sort by other
        levels too (in order) after sorting by specified level.
    ignore_index : bool, default False
        If True, the resulting axis will be labeled 0, 1, …, n - 1.
    key : callable, optional
        If not None, apply the key function to the index values
        before sorting. This is similar to the `key` argument in the
        builtin :meth:`sorted` function, with the notable difference that
        this `key` function should be *vectorized*. It should expect an
        ``Index`` and return an ``Index`` of the same shape. For MultiIndex
        inputs, the key is applied *per level*.

    Returns
    -------
    DataFrame or None
        The original DataFrame sorted by the labels or None if ``inplace=True``.

    See Also
    --------
    Series.sort_index : Sort Series by the index.
    DataFrame.sort_values : Sort DataFrame by the value.
    Series.sort_values : Sort Series by the value.

    Examples
    --------
    >>> df = pd.DataFrame([1, 2, 3, 4, 5], index=[100, 29, 234, 1, 150],
    ...                   columns=['A'])
    >>> df.sort_index()
         A
    1    4
    29   2
    100  1
    150  5
    234  3

    By default, it sorts in ascending order, to sort in descending order,
    use ``ascending=False``

    >>> df.sort_index(ascending=False)
         A
    234  3
    150  5
    100  1
    29   2
    1    4

    A key function can be specified which is applied to the index before
    sorting. For a ``MultiIndex`` this is applied to each level separately.

    >>> df = pd.DataFrame({"a": [1, 2, 3, 4]}, index=['A', 'b', 'C', 'd'])
    >>> df.sort_index(key=lambda x: x.str.lower())
       a
    A  1
    b  2
    C  3
    d  4

## df.drop()
删除字段

df.drop(field, axis)
- field 待删除的字段名
- axis 删除方向。1为列，0为行。或者'columns'为列，'rows'为行

In [13]:
df

      姓名  课程  成绩 性别
0  David  语文  98  男
1  David  数学  88  男
2  David  英语  79  男
3   Mary  语文  93  女
4   Mary  数学  97  女
5   Mary  英语  89  女

In [14]:
df.drop('姓名', axis=1)

   课程  成绩 性别
0  语文  98  男
1  数学  88  男
2  英语  79  男
3  语文  93  女
4  数学  97  女
5  英语  89  女

In [15]:
df.drop(0, axis=0)

      姓名  课程  成绩 性别
1  David  数学  88  男
2  David  英语  79  男
3   Mary  语文  93  女
4   Mary  数学  97  女
5   Mary  英语  89  女

In [16]:
df.drop(5, axis=0)

      姓名  课程  成绩 性别
0  David  语文  98  男
1  David  数学  88  男
2  David  英语  79  男
3   Mary  语文  93  女
4   Mary  数学  97  女

In [17]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(
    labels: 'IndexLabel | None' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel | None' = None,
    columns: 'IndexLabel | None' = None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise'
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [18]:
df

      姓名  课程  成绩 性别
0  David  语文  98  男
1  David  数学  88  男
2  David  英语  79  男
3   Mary  语文  93  女
4   Mary  数学  97  女
5   Mary  英语  89  女