# （一）`apply`：逐元素 / 逐行的“独立加工”

**数学直觉：**

> `apply` 的输入是单个元素或单行。
> 它做的是 **element-wise transformation（逐元素变换）**。
> 每个元素都独立进入函数，独立加工，独立输出。

**生活类比（贴切不幼稚）：**

> 把一堆苹果放在流水线，
> 工人对每一个苹果 **单独检查、单独贴标签**：
>
> * 大 → 贴“大果”
> * 小 → 贴“小果”
>   每个苹果都走一遍同样的加工流程。

**映射到你的例子：**

* `"male"` → 1
* `"female"` → 0
* `[99, 70, 83]` → 求最大值

每一个性别、每一个成绩列表都被单独“检查一次”。

 **关键特征：**

* 输入：一个个元素
* 输出：与原长度一致
* 功能：逐行加工、逐元素计算、列表处理

---

# （二）`agg`：整列 / 整组的“整体汇总”

**数学直觉：**

> `agg` 的输入是一整列（或分组后的整组）。
> 它做的是 **aggregation（汇总统计）**。
> 输出是“整体性的指标”：如和、平均值、最大值、最小值。

**生活类比（贴切实际）：**

> 不是对每个苹果单独贴标签，而是
> **把整箱苹果一起称重、数个数、算平均重量。**
> 关注的是“**这整箱苹果总体怎么样？**”

**映射到你的例子：**

* 全班最大分数是多少？
* 全班平均成绩是多少？

这些问题都不再关心每个学生如何，而是关注“整体水平”。

 **关键特征：**

* 输入：整列数据
* 输出：一个或少数几个统计值
* 功能：整体汇总、组间统计、维度缩减

# （三）总结

> **`apply`：像“流水线逐个加工物品”（独立处理每个元素）<br>
> `agg`：像“把整箱物品称重/统计”（对整体做汇总）**

# 批运算(操作)
|代码|功能|
|:---|:---|
|df['colname'].apply(func)|对df中的colname列实行func批运算|
|df.agg({'colname': func})|对df中的colname列实行func批运算|

apply的用法<br>
• apply 一定 跟着一个函数（func）使用<br>
• apply 的任务就是：把这个函数重复使用 N 次，对 N 个元素分别加工<br>
```python
Series.apply(func)
```
含义：<br>
• 你把一个函数 func 传给 apply<br>
• apply 会自动对这一列中的 每一个元素 执行一次 func<br>
可以理解为：<br>
apply 的“动力”来自你给它提供的函数。<br>
没有函数，apply 自己什么也做不了。<br>


apply 是如何“跟着函数”的？<br>
关键点：<br>
你传什么函数进去，apply 就对每个元素执行什么函数。<br>

agg 的基本结构（Series / DataFrame 上）<br>
✔ 对 Series 使用 agg<br>
```python
Series.agg(func)
```
✔ 对 DataFrame 使用 agg（对多列汇总）<br>
```python
DataFrame.agg({'col1': func1, 'col2': func2, ...})
```
agg 一定跟着统计函数使用：<br>
• 内置统计函数：'mean', 'max', 'min', 'std', 'sum'<br>
• NumPy 函数：np.mean, np.max<br>
• 自定义函数：自写 def 函数<br>

In [2]:
import pandas as pd

data = {'name': ['David', 'Mary', 'Henry', 'Smith'],
        'sex': ['male', 'female', 'male', 'male'],
        'grade': [[99, 70, 83], 
                  [77, 79, 83],
                  [87, 89, 94],
                  [88, 93, 95]]
       }


df = pd.DataFrame(data)
df

    name     sex         grade
0  David    male  [99, 70, 83]
1   Mary  female  [77, 79, 83]
2  Henry    male  [87, 89, 94]
3  Smith    male  [88, 93, 95]

### 问题
1. 将male替换为1， female替换为0, 结果保存到sex_code
2. 求最大值，保存到max_grade
3. 求最小值，保存到min_grade
4. 计算平均分，将结果保存到新字段 avg_grade 中

## 将male替换为1， female替换为0, 结果保存到sex_code

In [3]:
def sex2num(sex):
    if sex=='male':
        return 1
    else:
        return 0
    
df['sex_code'] = df['sex'].apply(sex2num)
df

    name     sex         grade  sex_code
0  David    male  [99, 70, 83]         1
1   Mary  female  [77, 79, 83]         0
2  Henry    male  [87, 89, 94]         1
3  Smith    male  [88, 93, 95]         1

## 求最大值，保存到max_grade

In [4]:

df['max_grade'] = df['grade'].apply(max)
df

    name     sex         grade  sex_code  max_grade
0  David    male  [99, 70, 83]         1         99
1   Mary  female  [77, 79, 83]         0         83
2  Henry    male  [87, 89, 94]         1         94
3  Smith    male  [88, 93, 95]         1         95

## 求最小值，保存到min_grade

In [5]:
df['min_grade'] = df['grade'].apply(min)
df

    name     sex         grade  sex_code  max_grade  min_grade
0  David    male  [99, 70, 83]         1         99         70
1   Mary  female  [77, 79, 83]         0         83         77
2  Henry    male  [87, 89, 94]         1         94         87
3  Smith    male  [88, 93, 95]         1         95         88

## 计算平均分，将结果保存到新字段 avg_grade 中

In [6]:
def my_mean(lst):
    return sum(lst)/len(lst)

df['avg_grade'] = df['grade'].apply(my_mean)
df

    name     sex         grade  sex_code  max_grade  min_grade  avg_grade
0  David    male  [99, 70, 83]         1         99         70  84.000000
1   Mary  female  [77, 79, 83]         0         83         77  79.666667
2  Henry    male  [87, 89, 94]         1         94         87  90.000000
3  Smith    male  [88, 93, 95]         1         95         88  92.000000

In [9]:
df.agg({'grade': "max"})

grade    [99, 70, 83]
dtype: object

In [14]:
df.agg({'grade':"min"})

grade    [77, 79, 83]
dtype: object

In [15]:
# 定义一个自定义聚合函数，用于计算整列中 "male" 的比例
def male_ratio(series):
    # series 是一整列数据（例如 df['sex']）
    # (series == 'male') 会生成一个布尔序列，如 [True, False, True, ...]
    # True 会被当作 1，False 当作 0
    # mean() 就是求平均值，也就是 "male 的占比"
    return (series == 'male').mean()


# 使用 agg 对整列进行“整体汇总”
# 把 sex 列整体传入 male_ratio(series)
result = df.agg({'sex': male_ratio})

# 查看输出结果（即：全列中 male 的比例）
result

sex    0.75
dtype: float64