一、数据去重（drop_duplicates）
在数据分析中，重复数据会影响统计结果、平均值、缺失值判断甚至模型训练的准确性，因此必须在清洗环节进行去重。
1. 为什么会有重复数据？
• 数据多次抓取、拼接时产生重复行
• 数据库导出时分批合并
• 手工录入错误
2. Pandas 的去重方法：df.drop_duplicates()
语法：
df.drop_duplicates(inplace=False)
参数说明：
• inplace=False：默认不修改原数据，只返回去重结果
• inplace=True：直接修改原 DataFrame
3. 去重默认规则
• 默认以整行数据完全一致才算重复
• 保留第一条出现的记录
二、缺失值处理（dropna / fillna）<br>
缺失值（NaN）在实际数据中非常常见，它会影响：<br>
统计量（mean/median）<br>
绘图<br>
机器学习模型训练<br>
因此需要提前处理。<br>
1. 检查缺失值<br>
常用方法：
```python
df.isnull().sum()
```
2. 删除缺失值：df.dropna()<br>
```python
df.dropna(axis=0, inplace=False)
```python
参数：<br>
axis=0：删除含有缺失值的行<br>
axis=1：删除含有缺失值的列<br>
inplace=True/False：是否原地修改<br>

删除的优点：<br>
✔ 简单、不引入假数据<br>

缺点：<br>
✘ 数据量减少<br>
✘ 若缺失严重会丢掉大量样本<br>

3. 填充缺失值：df.fillna()<br>

语法：
```python
df.fillna(value, inplace=False)
```
value 可以是：<br>
固定值：如 0<br>
均值/中位数<br>

字典：为不同列填不同值<br>
例如
```python
df.fillna({'temperature': 35, 'windspeed': 10, 'event': '没有记录'})
```
填充优点：<br>
✔ 不损失样本<br>
✔ 便于后续分析<br>
4. 字典填法的理解<br>
例如：<br>
```python
df.fillna({'temperature': 35, 'windspeed': 10, 'event': '没有记录'})
```
表示：<br>
temperature 列的 NaN → 填 35<br>
windspeed 列的 NaN → 填 10<br>
event 列的 NaN → 填 “没有记录”<br>
这样每列按照自己的业务逻辑填充，更科学。<br>

In [10]:
# 读取数据
import pandas as pd

df = pd.read_csv('nan_data.csv')
df

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         28.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         40.0       12.0   Sunny
9    1/1/2017         32.0        6.0    Rain
10   1/4/2017          NaN        9.0   Sunny
11   1/5/2017         28.0        NaN    Snow
12   1/6/2017          NaN        7.0     NaN
13   1/7/2017         32.0        NaN    Rain
14   1/8/2017          NaN        NaN   Sunny
15   1/9/2017          NaN        NaN     NaN
16  1/10/2017         34.0        8.0  Cloudy
17  1/11/2017         40.0       12.0   Sunny

# 查看是否有缺失值
- df.isna()  nan所在的位置返回True，正常数据返回False
- df.notna()  df.isna()反向操作

# 数据去重

DataFrame数据类型有去重方法


``df.drop_duplicates(inplace)``

inplace是否对df原始数据进行去重操作，inplace的值为True或者False

In [11]:
#非原地修改，没有对原始数据进行去重
df.drop_duplicates()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [12]:
#对原始数据去重
df.drop_duplicates(inplace=True)
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

# 常用的缺失值处理

- df.dropna(axis, inplace)  默认axis=0
- df.fillna(某个数or定义的字典, inplace)  填充


上述两种缺失值操作都有inplace参数可供使用

## df.dropna()

In [13]:
#默认axis=0，
df.dropna()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [14]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [15]:
df.dropna(axis=1)

         day
0   1/1/2017
1   1/4/2017
2   1/5/2017
3   1/6/2017
4   1/7/2017
5   1/8/2017
6   1/9/2017
7  1/10/2017
8  1/11/2017

In [16]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or sequence of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
    ...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    ...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
    ...                             pd.NaT]})
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis='columns')
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how='all')
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=['name', 'toy'])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [17]:
#axis=1，当该列全部数据都不是nan时，该列保留。
df.dropna(axis=1)

         day
0   1/1/2017
1   1/4/2017
2   1/5/2017
3   1/6/2017
4   1/7/2017
5   1/8/2017
6   1/9/2017
7  1/10/2017
8  1/11/2017

## df.fillna()
- 某个值填充
- 定义字典方式对每个字段进行填充

这个函数也是有inplace的

In [19]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [20]:
df.fillna(0)

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          0.0        9.0   Sunny
2   1/5/2017         28.0        0.0    Snow
3   1/6/2017          0.0        7.0       0
4   1/7/2017         32.0        0.0    Rain
5   1/8/2017          0.0        0.0   Sunny
6   1/9/2017          0.0        0.0       0
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [21]:
df.fillna({'temperature': 35,
 'windspeed': 10,
 'event': '没有记录'})

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         35.0        9.0   Sunny
2   1/5/2017         28.0       10.0    Snow
3   1/6/2017         35.0        7.0    没有记录
4   1/7/2017         32.0       10.0    Rain
5   1/8/2017         35.0       10.0   Sunny
6   1/9/2017         35.0       10.0    没有记录
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny